---
- hosts: all
  become: yes
  tasks:
- name: install ntp
  apt:
    pkg: ntp
    state: present
- name: install vim
  apt:
    pkg: vim
    state: present
- name: start ntp service
  service:
    name: ntp
    state: started
    enabled: true
- name: run update
  apt:
    update_cache: yes
